# Dependencies
highlighter:      pygments

# Setup
title:            JS
tagline:          'JS Tech Blog'
description:      'AI, Machine Learning, Data Analytics'
url:             ""
baseurl:         "https://jisoo920.github.io/"

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
