# Dependencies
highlighter:      rouge

# Setup
title:            JS
tagline:          'JS Tech Blog'
description:      'AI, Machine Learning, Data Analytics'
url:             ""
baseurl:         "https://jisoo920.github.io/"

author:
  name:           'Ji-Soo Kang'
  url:            dm.jskang@kyonggi.ac.kr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
