# Dependencies
highlighter:      rouge

# Setup
title:            Mining every little thing
tagline:          ''
description:      'AI, Machine Learning, Data Analytics'
url:             ""
baseurl:         "https://jisoo920.github.io/"

author:
  name:           'Ji-Soo Kang'
  url:            dm.jskang@kyonggi.ac.kr

paginate:         5

github:
  repo:           https://github.com/jisoo920/jisoo920.github.io
